#!/bin/bash
mkdir -p /root/omnetpp-5.6.2/samples
cd /root/omnetpp-5.6.2/samples
ln -s /models/labscim labscim
cd /root/LoRaMac-node
cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DAPPLICATION:STRING=LoRaMac -DSUB_PROJECT:STRING=periodic-uplink-lpp -DLORAWAN_DEFAULT_CLASS:STRING=CLASS_A -DCLASSB_ENABLED:STRING=ON -DACTIVE_REGION:STRING=LORAMAC_REGION_AU915 -DMODULATION:STRING=LORA -DBOARD:STRING=labscim -DMBED_RADIO_SHIELD:STRING=LABSCIM_SHIELD -DLORAMAC_LR_FHSS_IS_ON:STRING=ON -DSECURE_ELEMENT:STRING=SOFT_SE -DSECURE_ELEMENT_PRE_PROVISIONED:STRING=OFF -DREGION_EU868:STRING=ON -DREGION_US915:STRING=OFF -DREGION_CN779:STRING=OFF -DREGION_EU433:STRING=OFF -DREGION_AU915:STRING=ON -DREGION_CN470:STRING=OFF -DREGION_AS923:STRING=OFF -DREGION_KR920:STRING=OFF -DREGION_IN865:STRING=OFF -DREGION_RU864:STRING=OFF -DREGION_AS923_DEFAULT_CHANNEL_PLAN:STRING=CHANNEL_PLAN_GROUP_AS923_1 -DREGION_CN470_DEFAULT_CHANNEL_PLAN:STRING=CHANNEL_PLAN_20MHZ_TYPE_A -DUSE_RADIO_DEBUG:STRING=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++ -S/root/LoRaMac-node -B/root/LoRaMac-node/build -G Ninja .
cd build
ninja